config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'
  resources :items, only: [:index , :new , :create ,:edit ,:destroy , :show , :update]
  resources :items do
    resources :states , only: [:index , :new , :create , :update , :edit , :destroy ]
  end
  resources :states do
    collection do
      get 'search'
      get 'alarm'
      get 'search_limit'
    end
    member do
      get 'search_firstinout'
      get 'search_lastinout'
      get 'search_exdate'
    end
  end

  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true

  belongs_to :user
  has_one_attached :image
  has_many :states

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :limit

end

app/models/limit.rb
class Limit < ActiveHash::Base
 self.data = [
   { id: 1, name: '---' },
   { id: 2, name: 'あり' },
   { id: 3, name: 'なし' }
 ]

  include ActiveHash::Associations
  has_many :states

 end

app/models/state.rb
class State < ApplicationRecord

  with_options presence: true do
    validates :quantity , format: { with: /\A[0-9]+\z/ }
    validates :unit_id
    validates :limit_id
    validates :storage_name , format: { with:  /\A[a-zA-Zａ-ｚＡ-ｚぁ-んァ-ヶ一-龥々ー]+\z/ }
    validates :storage_address
  end

  with_options numericality: { other_than: 1 } do
    validates :unit_id
    validates :limit_id
  end

  validates :quantity, numericality: { greater_than_or_equal_to: 1 }
  validates :quantity, numericality: { less_than_or_equal_to: 9_999_999 }

  belongs_to :item

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :limit
  belongs_to :unit

end

app/models/unit.rb
class Unit < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '個' },
    { id: 3, name: '台' },
    { id: 4, name: '枚' },
    { id: 5, name: 'セット' },
    { id: 6, name: '本' },
    { id: 7, name: '冊' },
  ]

   include ActiveHash::Associations
   has_many :states

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items

  with_options presence: true do
    validates :name , format: { with: /\A[ぁ-んァ-ン一-龥々]/ }
    validates :address
    validates :password , format: { with: /[a-zA-Z]{1,}+[0-9]{1,}/ }
  end

  has_many :items
  has_many :orders  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :devise_patameters, if: :devise_controller?
before_action :set_date

private
def devise_patameters
  devise_parameter_sanitizer.permit(:sign_up,keys: [:name,:address,:alarm_email] )
end

def set_date
  @today = Date.today
end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @today = Date.today
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      @user_mail = current_user.email
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
    @today = Date.today
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    @item = Item.find(params[:id])
    @states = State.where(item_id: params[:id])
    @today = Date.today
  end

  def destroy
    @item = Item.find(params[:id])
    if @item.destroy
      redirect_to root_path
    end
  end

  private

  def item_params
    params.require(:item).permit(:name,:information,:image).merge(user_id: current_user.id)
  end


end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_item, only: [:new,:create,:edit,:update,:destroy]

  def new
    @state = State.new
  end

  def create
    @state = State.new(state_params)
    if @state.save
      redirect_to "/items/#{params[:item_id]}"
    else
      render action: :new
    end
  end

  def edit
    @state = State.find(params[:id])
  end

  def update
    @state = State.find(params[:id])
    if @state.update(state_params)
      redirect_to "/items/#{params[:item_id]}"
    else
      render :edit
    end
  end


  def destroy
    @state = State.find(params[:id])
    if @state.destroy
      redirect_to "/items/#{params[:item_id]}"
    end
  end

  def search
    @items = Item.all
  end

  def search_firstinout
    @item = Item.find(params[:id])
    @states = State.where(item_id: params[:id]).order("created_at ASC")
  end

  def search_lastinout
    @item = Item.find(params[:id])
    @states = State.where(item_id: params[:id]).order("created_at DESC")
  end

  def search_exdate
    @item = Item.find(params[:id])
    @states = State.where(item_id: params[:id]).order("limit_day ASC")
  end

  def alarm
    @items = Item.all
    @states = State.all

    @user_mail = current_user.alarm_email
    if AlarmMailer.alarm_mail(@user_mail,@items,@states,@today).deliver
      redirect_to root_path
    end
  end

  def search_limit
    @states = State.all.order("item_id ASC")
    @under_limit = []
    @under_day_alarm = []
    @over_limit = []
    @over_day_alarm = []
    @states.each do |state|
      if state.limit_id == 2
        limit_day = state.limit_day.to_date
        alarm = limit_day - @today
        if alarm <= 10 && 0 <= alarm
          @under_limit << state
          @under_day_alarm << alarm
        else alarm < 0
          @over_limit << state
          @over_day_alarm << alarm
        end
      end
    end
  end

  private

  def state_params
    params.require(:state).permit(:quantity,:unit_id,:limit_id,:limit_day,:storage_name,:storage_address).merge(item_id: params[:item_id])
  end

  def set_item
    @item = Item.find(params[:item_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/items/_new_form.html.erb
<div class="form">
  <div class ="new_item_regist" >
  <p>新しい商品を登録できます。</p>
  <p>商品の画像と名称を入力してください。</p>
  <p>※画像は任意で登録できます。</p>
  </div>
  <%= form_with(model: @item, local: true) do |form| %>
    <div class ="image_select " >画像の選択</div>
    <%= form.file_field :image, placeholder: "画像" ,class: :new_image_form %>
    <div class = "new_item_name" >商品の名称 </div>
    <%= form.text_field :name, placeholder: "商品名" ,class: :new_name_form %>
    <%= form.submit "登録" ,class: :new_submit_form %>
  <% end %>
</div>

app/views/items/alarm.html.erb
<%# アラーム表示画面 %>
<div class="hidden" id="alarm-test" >
  <div class = "show-list">
    <div>
      <div>
        使用期限まで１０日以内の製品 -----------------
      </div>
      <% if @states.present?%>
        <% @items.zip(@states).each do |item,state|%>
          <%if state.limit_id == 2 %>
            <% limit_day = state.limit_day.to_date %>
            <% alarm = limit_day - @today %>
              <% if alarm <= 10 && 0 <= alarm %>
                <%= "Item：#{item.name}" %>
                <table class = "show_table_total">
                  <tr class = "show_table_tr">
                    <th class = "show_table_th" >ID</th>
                    <th class = "show_table_th" >残り日数</th>
                    <th class = "show_table_th" >使用期限</th>
                  </tr>
                  <tr class = "show_state">
                    <td class = show_state_td><%= "#{state.id}"%></td>
                    <td class = show_state_td><%= "#{alarm.to_i}日"%></td>
                    <td class = show_state_td><%= "#{state.limit_day.strftime("%Y年%m月%d日")}"%></td>
                  </tr>
                </table>
              <% end %>
          <% end %>
        <% end %>
      <% else %>
        <div>
          該当商品はありません。
        </div>
      <% end %>
    </div>

    <div>
      <div>
        使用期限を超えた製品 -----------------------
      </div>
      <% if @states.present?%>
        <% @items.zip(@states).each do |item,state|%>
          <%if state.limit_id == 2 %>
            <% limit_day = state.limit_day.to_date %>
            <% alarm = limit_day - @today %>
            <div>
              <% if alarm < 0 %>
                <%= "Item：#{item.name}" %>
                <table class = "show_table_total">
                  <tr class = "show_table_tr">
                    <th class = "show_table_th" >ID</th>
                    <th class = "show_table_th" >＊使用期限切れ＊</th>
                    <th class = "show_table_th" >使用期限</th>
                  </tr>
                  <tr class = "show_state">
                    <td class = show_state_td><%= "#{state.id}"%></td>
                    <td class = show_state_td><%= "期限から【#{alarm.to_i.abs}日】経過"%></td>
                    <td class = show_state_td><%= "#{state.limit_day.strftime("%Y年%m月%d日")}"%></td>
                  </tr>
                </table>
              <% end %>
            </div>
          <% end %>
        <% end %>
      <% else %>
        <div>
        該当商品はありません。
        </div>
      <% end %>
    </div>
  </div> 
</div>


<div>
  <div>
  使用期限を超えた製品 -----------------------
  </div>
  <% if @states.present?%>
    <% @items.zip(@states).each do |item,state|%>
      <% if state.limit_id == 2 %>
          <% limit_day = state.limit_day.to_date %>
          <% alarm = limit_day - @today %>
          <div>
            <% if alarm < 0 %>
              <%= "Item：#{item.name}" %>
              <table class = "show_table_total">
                <tr class = "show_table_tr">
                  <th class = "show_table_th" >ID</th>
                  <th class = "show_table_th" >＊使用期限切れ＊</th>
                  <th class = "show_table_th" >使用期限</th>
                </tr>
                <tr class = "show_state">
                  <td class = show_state_td><%= "#{state.id}"%></td>
                  <td class = show_state_td><%= "期限から【#{alarm.to_i.abs}日】経過"%></td>
                  <td class = show_state_td><%= "#{state.limit_day.strftime("%Y年%m月%d日")}"%></td>
                </tr>
              </table>
            <% end %>
          </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/items/edit.html.erb
<%= render "shared/header" %>

<%# 部分テンプレート %>
<div class="tatal_page">
  <%# サイドバー読み込み %>
  <div class="side_bar" >
    <%= render "shared/side_bar" %>
  </div>

  <%# メインページ読み込み %>
  <div class="items_form" >
    <div>
      <div class = "menu_title" >
        商品情報編集
      </div>
      <%= form_with(model: @item, local: true) do |form| %>
          <div class ="image_select " >
            画像の選択
          </div>
          <%= form.file_field :image, placeholder: "画像" ,class: :new_image_form %>

          <div class = "new_item_name" >
            商品の名称
          </div>
          <%= form.text_field :name, placeholder: "名称を入力して下さい" ,class: :new_name_form %>

          <div class = "new_item_name" >
            商品の説明
          </div>
          <%= form.text_area :information, placeholder: "商品の説明を入力出来ます。" ,class: :new_info_form %>

          <div class = "new_item_submit" >
            <%= form.submit "変更" ,class: :new_submit_form %>
          </div>
      <% end %>

      <div class = "top_page_link_base">
        <%= link_to '戻る', "/items/#{@item.id}",class: "search_method" %>
      </div>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<%= render "shared/header" %>

<% if user_signed_in? %>
  <%# 部分テンプレート %>
  <div class="tatal_page">

    <%# サイドバー読み込み %>
    <div class="side_bar" >
      <%= render "shared/side_bar" %>
    </div>

    <%# メインページ読み込み %>
    <div class="main_page" >
      <% @items.each_with_index do |item,index| %>
        <% if current_user.id == item.user_id %>
          <div class = "item_box" >
              <div class = "main_page_state_box" >
                <% if item.image.present? %>
                  <div>
                   <%= image_tag item.image , class: 'image_box' if item.image.attached?  %>
                  </div>
                    <div>
                    <%= link_to '在庫管理',"/items/#{item.id}" , class: :search_method  %>
                  </div>
                <% else %>
                    <div class = "no_image">
                      Noimage
                    </div>
                  <div class = "space">
                  </div>
                  <div>
                    <%= link_to '在庫管理',"/items/#{item.id}" , class: :search_method  %>
                  </div>
                <% end %>
              </div>
              <div  class = "main_table_total" >
              <table>
                <tr class = "main_page_state">
                  <th class = "main_page_table_th" > index： </th>
                  <td class = "main_page_state_td"> <%= index+1 %> </td>
                </tr>
                <tr class = "main_page_state">
                  <th class = "main_page_table_th" > ID： </th>
                  <td class = "main_page_state_td"> <%= item.id%> </td>
                </tr>
                <tr class = "main_page_state">
                  <th class = "main_page_table_th" > Item： </th>
                  <td class = "main_page_state_td"> <%= item.name%> </td>
                </tr>
              </table>
            </div>
            <div>
              <div  class = "item_info_index" >
                商品説明
              </div>
              <div class = "item_info"><%=item.information%></div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
<% else %>
  <img src="/assets/top_page.jpg" alt="トップページ" title="top_page" class="top_image">
  <div class="sing_in_page">
    <div class = "sing_in_box">
      <div class = "sing_in_botn">
        <%= link_to "ログイン", new_user_session_path, class: "command" %>
      </div>
      <div class = "sing_up_botn">
        <%= link_to '新規ユーザー登録ページ', new_user_registration_path, class: "command" %>
      </div>
    </div>
  </div>
<% end %>

app/views/items/new.html.erb
<%= render "shared/header" %>

<%# 部分テンプレート %>
  <div class="tatal_page">
    <%# サイドバー読み込み %>
    <div class="side_bar" >
      <%= render "shared/side_bar" %>
    </div>
    <%# メインページ読み込み %>
    <div class="items_form" >
      <div>
        <div class = "menu_title" >
        商品新規登録
        </div>
        <div class="form">
          <div class ="new_item_regist" >
            <p>新しい商品を登録できます。</p>
            <p>商品の画像と名称を入力してください。</p>
            <p>　</p>
            <p>※画像は任意で登録できます。</p>
          </div>
          <p>　</p>
          <%= form_with(model: @item, local: true) do |form| %>
            <div class ="image_select " >
              画像の選択
            </div>
            <%= form.file_field :image, placeholder: "画像" ,class: :new_image_form %>

            <div class = "new_item_name" >
              商品の名称
            </div>
              <%= form.text_field :name, placeholder: "名称を入力して下さい" ,class: :new_name_form %>

            <div class = "new_item_name" >
              商品の説明
            </div>
              <%= form.text_area :information, placeholder: "商品の説明を入力出来ます。" ,class: :new_info_form %>

            <div class = "new_item_submit" >
              <%= form.submit "登録" ,class: :new_submit_form %>
            </div>
          <% end %>
        </div>
        <div class = "top_page_link_base">
        </div>
      </div>
    </div>

  </div>

app/views/items/show.html.erb
<%= render "shared/header" %>

<div class="tatal_page">
  <%# サイドバー読み込み %>
  <div class="side_bar" >
    <%= render "shared/side_bar" %>
  </div>

  <%# メインページ %>
  <div class="show_main" >
    <div class = "show_box">
      <div class = "menu_title" >
        在庫管理
      </div>


    <div class = "image_and_info">
      <% if @item.image.present? %>
        <div>
          <%= image_tag @item.image, class: 'show_image' if @item.image.attached?  %>
        </div>
      <% else %>
        <div class = "no_image">
          Noimage
        </div>
      <% end %>

        <div>
          <div class = "item_info" ><%= @item.information %></div>
        </div>
      </div>

      <div class = "show_itemname">
        Item：<%= @item.name %>
      </div>

      <div class = "show_frame_total">
        <%= link_to 'edit(編集)',"/items/#{@item.id}/edit",method: :get  , class: :show_frame %>
        <%= link_to 'Delete(削除)',"/items/#{@item.id}",method: :delete , data: { confirm: '削除してよいですか？' }  , class: :show_frame %>
        <%= link_to '在庫追加',"/items/#{@item.id}/states/new"  , class: :show_frame %>
        <%= link_to '一覧に戻る',root_path , class: :show_frame %>
      </div>

      <table class = "show_table_total">
        <tr class = "show_table_tr">
          <th class = "show_table_th" >ID</th>
          <th class = "show_table_th" >入庫日</th>
          <th class = "show_table_th" >数量</th>
          <th class = "show_table_th" >保管場所</th>
          <th class = "show_table_th" >住所</th>
          <th class = "show_table_th" >使用期限</th>
        </tr>

        <% @states.each do |state| %>
          <tr class = "show_state">
            <td class = show_state_td><%= state.id %></td>
            <td class = show_state_td><%= state.created_at.strftime("%Y年%m月%d日") %></td>
            <td class = show_state_td><%= state.quantity %><%= state.unit.name %></td>
            <td class = show_state_td><%= state.storage_name %></td>
            <td class = show_state_td><%= state.storage_address %></td>
              <% if state.limit_id == 3 %>
                <td class = show_state_td><%= state.limit.name %></td>
              <% else state.limit_id == 2 %>
                <td class = show_state_td><%= state.limit_day.strftime("%Y年%m月%d日") %></td>
              <% end %>
            <td class = show_state_td><%= link_to "編集" , "/items/#{@item.id}/states/#{state.id}/edit" , class: :show_frame %>
            <td class = show_state_td><%= link_to '削除',"/items/#{@item.id}/states/#{state.id}",method: :delete , data: { confirm: '削除してよいですか？' }  , class: :show_frame %>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pocket_Warehouse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <meta charset="UTF-8">

  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<div class = "header">
  <div class="today_date_bar"> 
    <div class ="today">
      <%="TODAY"%>
    </div>
    <span class = "today_date">
      <%= @today.strftime("%Y年%m月%d日") %>
    </span>
  </div>


  <div class="site_icon_base">
    <div class="site_name">
    Pocket
    </div>
    <%= link_to image_tag("icon.png", class: :site_icon), root_path %>
    <div class="site_name">
    Warehouse
    </div>
  </div>
</div>

app/views/shared/_side_bar.html.erb
<div>

  <%# ユーザー情報 %>
  <div class = "name_content">
    <% if user_signed_in? %>
      <div class = "user_tag">User</div>
      <%= link_to current_user.name, "#" , class: "name" %>
    <%else%>
      <div> <%= link_to "ログイン", new_user_session_path%></div>
    <% end %>
  </div>

  <%# コマンドリスト %>
  <div class = "command_list">
    <% if user_signed_in? %>
      <%= link_to '商品一覧表示', root_path , class: "command" %>
      <%= link_to '商品登録', new_item_path , class: "command" %>
      <%= link_to "サーチ" , search_states_path, class: "command" %>
      <%= button_to "アラーム発生ボタン" , { controller: 'states', action:'search_limit'},{ method: :get , class: "alarm"  , id: :alarm_id } %>
      <%= button_to "メール通知ボタン" , { controller: 'states', action:'alarm'},{ method: :get , class: "alarm" , id: :email_id } %>
    <% else %>
      <%= link_to '新規ユーザー登録ページ', new_user_registration_path, class: "command" %>
    <% end %>
  </div>

  <div class = "logout">
    <% if user_signed_in? %>
      <%= link_to 'ログアウト',destroy_user_session_path , method: :delete, class: "command" %>
    <% end %>
  </div>
</div>

app/views/states/_state_form.html.erb
<div class = "state_new">
  <%= image_tag @item.image , class: 'state_new_image' if @item.image.attached?   %>
  <div class = "sate_new_item_name">
    商品名：<%= @item.name%>
  </div>

  <% if @state.id.present?%>
  <div class = "item_id">
    ID： <%= @state.id %>
  </div>
  <% end %>

  <%= form_with(model:[@item, @state], local: true) do |form| %>
    <div class = "state_quantitiy_index" >
      数量・単位を入力して下さい。[数量は1〜9,999,999まで入力できます]
    </div>
      <%= form.text_field :quantity,class: :state_quantitiy_form , placeholder: "在庫数を入力"%>
      <%= form.collection_select(:unit_id, Unit.all, :id , :name, {},{class:"quantitiy_unit"} ) %>

    <div class = "state_storage_name_index">
      保管場所の名称
    </div>
      <%= form.text_field :storage_name, placeholder: "名称を入力して下さい",class:"state_storage_name" %>

    <div class = "state_storage_address_index">
      保管場所の住所
    </div>
      <%= form.text_field :storage_address, placeholder: "場所を入力して下さい",class:"state_storage_address"%>

    <div class = "state_limit_index">
      使用期限は設定しますか  </div>
    <%= form.collection_select(:limit_id, Limit.all, :id, :name, {}, {class:"state_limit"}) %>

    <div class = "state_limit_date_index" >
      期日
    </div>
      <%= form.date_select :limit_day ,{use_month_numbers: true,discard_hour: true,date_separator: '/' }, {class: "state_limit_date"} %>

    <div class = "subimt_form" >
        <%= form.submit "登録" ,class: :state_submit %>
    </div>

    <div class = "state_link_box" >
        <%= link_to '戻る',"/items/#{@item.id}",class: "search_method" %>
    </div>
  <% end %>
</div>

app/views/states/_state_search.html.erb
<div class = "image_and_info">
  <%= image_tag @item.image , class: :show_image %>
  <div>
    <div class = "item_info"><%= @item.information %></div>
  </div>
</div>

<div class = "show_itemname">
  商品名：<%= @item.name %>
</div>

<div class = "show_frame_total">
  <%= link_to 'edit(編集)',"/items/#{@item.id}/edit",method: :get  , class: :show_frame %>
  <%= link_to 'Delete(削除)',"/items/#{@item.id}",method: :delete , data: { confirm: '削除してよいですか？' }  , class: :show_frame %>
  <%= link_to '在庫追加',"/items/#{@item.id}/states/new"  , class: :show_frame %>
  <%= link_to '戻る',search_states_path , class: :show_frame %>
</div>

<table class = "show_table_total">
  <tr class = "show_table_tr">
    <th class = "show_table_th" >出荷順</th>
    <th class = "show_table_th" >id</th>
    <th class = "show_table_th" >数量</th>
    <th class = "show_table_th" >保管場所</th>
    <th class = "show_table_th" >住所</th>
    <th class = "show_table_th" >入庫日</th>
    <th class = "show_table_th" >使用期限</th>
  </tr>

  <% @states.each_with_index do |state,index| %>
    <tr class = "show_state">
      <td class = show_state_td><%= index + 1 %></td>
      <td class = show_state_td><%= state.id %></td>
      <td class = show_state_td><%= state.quantity %><%= state.unit.name %></td>
      <td class = show_state_td><%= state.storage_name %></td>
      <td class = show_state_td><%= state.storage_address %></td>
      <td class = show_state_td><%= state.created_at.strftime("%Y年%m月%d日") %></td>
        <% if state.limit_id == 3 %>
          <td class = show_state_td><%= state.limit.name %></td>
        <% else state.limit_id == 2 %>
          <td class = show_state_td><%= state.limit_day.strftime("%Y年%m月%d日") %></td>
        <% end %>
      <td class = show_state_td><%= link_to '削除',"/items/#{@item.id}/states/#{state.id}",method: :delete , data: { confirm: '削除してよいですか？' }  , class: :show_frame %>
    </tr>
  <% end %>
</table>

app/views/states/search_exdate.erb
<%= render "shared/header" %>

<div class="tatal_page">
  <%# サイドバー読み込み %>
  <div class="side_bar" >
    <%= render "shared/side_bar" %>
  </div>

  <%# メインページ %>
  <div class="show_main" >
    <div class = "show_box">
      <div class = "menu_title" >
        使用期限優先
      </div>

      <div class = "image_and_info">
        <%= image_tag @item.image , class: :show_image %>
        <div>
          <div class = "item_info" ><%= @item.information %></div>
        </div>
      </div>


      <div class = "show_itemname">
        商品名：<%= @item.name %>
      </div>

      <div class = "show_frame_total">
        <%= link_to 'edit(編集)',"/items/#{@item.id}/edit",method: :get  , class: :show_frame %>
        <%= link_to 'Delete(削除)',"/items/#{@item.id}",method: :delete , data: { confirm: '削除してよいですか？' }  , class: :show_frame %>
        <%= link_to '在庫追加',"/items/#{@item.id}/states/new"  , class: :show_frame %>
        <%= link_to '戻る',search_states_path , class: :show_frame %>
      </div>

      <table class = "show_table_total">
        <tr class = "show_table_tr">
          <th class = "show_table_th" >出荷順</th>
          <th class = "show_table_th" >id</th>
          <th class = "show_table_th" >数量</th>
          <th class = "show_table_th" >保管場所</th>
          <th class = "show_table_th" >住所</th>
          <th class = "show_table_th" >入庫日</th>
          <th class = "show_table_th" >使用期限</th>
        </tr>

        <% index = 1 %>
        <% @states.each do |state| %>
          <% if state.limit_id == 2 %>
            <tr class = "show_state">
              <td class = show_state_td><%= index += 1 %></td>
              <td class = show_state_td><%= state.id %></td>
              <td class = show_state_td><%= state.quantity %><%= state.unit.name %></td>
              <td class = show_state_td><%= state.storage_name %></td>
              <td class = show_state_td><%= state.storage_address %></td>
              <td class = show_state_td><%= state.created_at.strftime("%Y年%m月%d日") %></td>
              <td class = show_state_td><%= state.limit_day.strftime("%Y年%m月%d日") %></td>
              <td class = show_state_td><%= link_to "編集" , "/items/#{@item.id}/states/#{state.id}/edit" , class: :show_frame %>
              <td class = show_state_td><%= link_to '削除',"/items/#{@item.id}/states/#{state.id}",method: :delete , data: { confirm: '削除してよいですか？' }  , class: :show_frame %>
            </tr>
          <% else state.limit_id == 3 %>
            <% index -= 1 %>
          <% end %>
        <% end %>
      </table>

      <table class = "show_table_total">
        <tr class = "show_table_tr">
          <th class = "show_table_th" >id</th>
          <th class = "show_table_th" >数量</th>
          <th class = "show_table_th" >保管場所</th>
          <th class = "show_table_th" >住所</th>
          <th class = "show_table_th" >入庫日</th>
          <th class = "show_table_th" >使用期限</th>
        </tr>

        <% @states.each do |state| %>
          <% if state.limit_id == 3 %>
            <tr class = "show_state">
              <td class = show_state_td><%= state.id %></td>
              <td class = show_state_td><%= state.quantity %><%= state.unit.name %></td>
              <td class = show_state_td><%= state.storage_name %></td>
              <td class = show_state_td><%= state.storage_address %></td>
              <td class = show_state_td><%= state.created_at.strftime("%Y年%m月%d日") %></td>
              <td class = show_state_td><%= state.limit.name %></td>
              <td class = show_state_td><%= link_to "編集" , "/items/#{@item.id}/states/#{state.id}/edit" , class: :show_frame %>
              <td class = show_state_td><%= link_to '削除',"/items/#{@item.id}/states/#{state.id}",method: :delete , data: { confirm: '削除してよいですか？' }  , class: :show_frame %>
           </tr>
          <% end %>
        <% end %>
      </table>
    </div>
  </div>
</div>